package guru.sfg.beer.order.service.domain;

public enum BeerOrderEventEnum {
    VALIDATION_ORDER, VALIDATION_PASS, VALIDATION_FAILED,
    ALLOCATE_ORDER, ALLOCATION_SUCCESS, ALLOCATION_NO_INVENTORY, ALLOCATION_FAILED,
    BEER_ORDER_PICKED_UP
}
